export const ADMIN_COURSE_LIST_REQUEST = "ADMIN_COURSE_LIST_REQUEST";
export const ADMIN_COURSE_LIST_FAIL = "ADMIN_COURSE_LIST_FAIL";
export const ADMIN_COURSE_LIST_SUCCESS = "ADMIN_COURSE_LIST_SUCCESS";

export const ADMIN_COURSE_DETAILS_REQUEST = "ADMIN_COURSE_DETAILS_REQUEST";
export const ADMIN_COURSE_DETAILS_SUCCESS = "ADMIN_COURSE_DETAILS_SUCCESS";
export const ADMIN_COURSE_DETAILS_FAIL = "ADMIN_COURSE_DETAILS_FAIL";

export const ADMIN_UPDATE_COURSE_REQUEST = "ADMIN_UPDATE_COURSE_REQUEST";
export const ADMIN_UPDATE_COURSE_SUCCESS = "ADMIN_UPDATE_COURSE_SUCCESS";
export const ADMIN_UPDATE_COURSE_FAIL = "ADMIN_UPDATE_COURSE_FAIL ";
